TARGETS	= $(OBJDIR)libtest.la $(OBJDIR)libs\ p\ a\ c\ e.la
OBJDIR	=
PREFIX	= /usr/local
DESTDIR	=
LIBDIR	= $(PREFIX)/lib
LDFLAGS	= -ldl -lintl  -ltest 
EXEEXT	=
AR	= ar
ARFLAGS	= -rc
RANLIB	= ranlib
CCSHARED= $(CC) -dynamiclib
SOEXT	= .dylib
LIBTOOL	= libtool
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

libtest_OBJS = $(OBJDIR)test.lo
libtest_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
libtest_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)libtest.la: $(libtest_OBJS)
	$(LIBTOOL) --mode=link --tag=CC $(CC) -o $(OBJDIR)libtest.la $(libtest_OBJS) -rpath $(LIBDIR) $(libtest_LDFLAGS)

libs_p_a_c_e_OBJS = $(OBJDIR)s\ p\ a\ c\ e.lo
libs_p_a_c_e_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
libs_p_a_c_e_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)libs\ p\ a\ c\ e.la: $(libs_p_a_c_e_OBJS)
	$(LIBTOOL) --mode=link --tag=CC $(CC) -o $(OBJDIR)libs\ p\ a\ c\ e.la $(libs_p_a_c_e_OBJS) -rpath $(LIBDIR) $(libs_p_a_c_e_LDFLAGS)

$(OBJDIR)test.o $(OBJDIR)test.lo: test.c
	$(LIBTOOL) --mode=compile --tag=CC $(CC) $(libtest_CFLAGS) -o $(OBJDIR)test.o -c test.c

$(OBJDIR)s\ p\ a\ c\ e.o $(OBJDIR)s\ p\ a\ c\ e.lo: s\ p\ a\ c\ e.c
	$(LIBTOOL) --mode=compile --tag=CC $(CC) $(libs_p_a_c_e_CFLAGS) -o $(OBJDIR)s\ p\ a\ c\ e.o -c s\ p\ a\ c\ e.c

clean:
	$(RM) -- $(libtest_OBJS) $(libs_p_a_c_e_OBJS)

distclean: clean
	$(RM) -- $(TARGETS)

install: all
	$(MKDIR) $(DESTDIR)$(LIBDIR)
	$(LIBTOOL) --mode=install $(INSTALL) -m 0755 $(OBJDIR)libtest.la $(DESTDIR)$(LIBDIR)/libtest.la
	$(LIBTOOL) --mode=finish $(DESTDIR)$(LIBDIR)
	$(MKDIR) $(DESTDIR)$(LIBDIR)
	$(LIBTOOL) --mode=install $(INSTALL) -m 0755 $(OBJDIR)libs\ p\ a\ c\ e.la $(DESTDIR)$(LIBDIR)/libs\ p\ a\ c\ e.la
	$(LIBTOOL) --mode=finish $(DESTDIR)$(LIBDIR)

uninstall:
	$(LIBTOOL) --mode=uninstall $(RM) -- $(DESTDIR)$(LIBDIR)/libtest.la
	$(LIBTOOL) --mode=uninstall $(RM) -- $(DESTDIR)$(LIBDIR)/libs\ p\ a\ c\ e.la

.PHONY: all clean distclean install uninstall
