TARGETS	= $(OBJDIR)test.dylib
OBJDIR	=
PREFIX	= /usr/local
DESTDIR	=
LIBDIR	= $(PREFIX)/lib
AR	= ar
RANLIB	= ranlib
CCSHARED= $(CC) -dynamiclib
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

test_OBJS = $(OBJDIR)test.o
test_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
test_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)test.dylib: $(test_OBJS) a.c b.c
	$(CCSHARED) -o $(OBJDIR)test.dylib $(test_OBJS) $(test_LDFLAGS)

$(OBJDIR)test.o: test.c
	$(CC) $(test_CFLAGS) -o $(OBJDIR)test.o -c test.c

clean:
	$(RM) -- $(test_OBJS)

distclean: clean
	$(RM) -- $(TARGETS)

install: $(TARGETS)
	$(MKDIR) $(DESTDIR)$(LIBDIR)/configure
	$(INSTALL) -m 0755 $(OBJDIR)test.dylib $(DESTDIR)$(LIBDIR)/configure/test.dylib

uninstall:
	$(RM) -- $(DESTDIR)$(LIBDIR)/configure/test.dylib

.PHONY: all clean distclean install uninstall
