TARGETS	= $(OBJDIR)object.o $(OBJDIR)object2.o $(OBJDIR)object3.o
OBJDIR	=
PREFIX	= /usr/local
DESTDIR	=
BINDIR	= $(PREFIX)/bin
SBINDIR	= $(PREFIX)/sbin
EXEEXT	=
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

object.o_OBJS = $(OBJDIR)object.o
object.o_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)

object2.o_OBJS = $(OBJDIR)object2.o
object2.o_ASFLAGS = $(ASFLAGSF) $(ASFLAGS)

object3.o_OBJS = $(OBJDIR)object3.o
object3.o_CPPFLAGS = $(CPPFLAGSF) $(CPPFLAGS) -nostdinc
object3.o_ASFLAGS = $(ASFLAGSF) $(ASFLAGS)

$(OBJDIR)object.o: object.c a.c b.c
	$(CC) $(object.o_CFLAGS) -o $(OBJDIR)object.o -c object.c

$(OBJDIR)object2.o: object2.asm
	$(AS) $(object2.o_ASFLAGS) -o $(OBJDIR)object2.o object2.asm

$(OBJDIR)object3.o: object3.S
	$(AS) $(object3.o_CPPFLAGS) $(object3.o_ASFLAGS) -o $(OBJDIR)object3.o object3.S

clean:
	$(RM) -- $(object.o_OBJS) $(object2.o_OBJS) $(object3.o_OBJS)

distclean: clean
	$(RM) -- $(TARGETS)

install: all
	$(MKDIR) $(DESTDIR)$(LIBDIR)
	$(INSTALL) -m 0644 $(OBJDIR)object.o $(DESTDIR)$(LIBDIR)/object.o

uninstall:
	$(RM) -- $(DESTDIR)$(LIBDIR)/object.o

.PHONY: all clean distclean install uninstall
