TARGETS	= phony target
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

phony:
	exit 42

target:
	$(MAKE) command

clean:
	$(RM) --

distclean: clean
	$(RM) -- $(TARGETS)

install: all

uninstall:

.PHONY: all clean distclean install uninstall phony
