TARGETS	= $(OBJDIR)test$(EXEEXT) $(OBJDIR)test2$(EXEEXT) $(OBJDIR)test3$(EXEEXT)
OBJDIR	=
PREFIX	= /Apps/$(VENDOR)
DESTDIR	=
BINDIR	= $(PREFIX)/Binaries
SBINDIR	= $(PREFIX)/Binaries
EXEEXT	=
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

test_OBJS = $(OBJDIR)test.o $(OBJDIR)main.o
test_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
test_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)test$(EXEEXT): $(test_OBJS)
	$(CC) -o $(OBJDIR)test$(EXEEXT) $(test_OBJS) $(test_LDFLAGS)

test2_OBJS = $(OBJDIR)test.o
test2_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
test2_LDFLAGS = $(LDFLAGSF) $(LDFLAGS) -lobjc

$(OBJDIR)test2$(EXEEXT): $(test2_OBJS)
	$(CC) -o $(OBJDIR)test2$(EXEEXT) $(test2_OBJS) $(test2_LDFLAGS)

test3_OBJS = $(OBJDIR)test.o
test3_CXXFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CXXFLAGSF) $(CXXFLAGS)
test3_LDFLAGS = $(LDFLAGSF) $(LDFLAGS) -ldl -lsocket -lm

$(OBJDIR)test3$(EXEEXT): $(test3_OBJS)
	$(CC) -o $(OBJDIR)test3$(EXEEXT) $(test3_OBJS) $(test3_LDFLAGS)

$(OBJDIR)test.o: test.c
	$(CC) $(test_CFLAGS) -o $(OBJDIR)test.o -c test.c

$(OBJDIR)main.o: main.c
	$(CC) $(test_CFLAGS) -o $(OBJDIR)main.o -c main.c

$(OBJDIR)test.o: test.m
	$(CC) $(test2_CFLAGS) -o $(OBJDIR)test.o -c test.m

$(OBJDIR)test.o: test.cpp
	$(CXX) $(test3_CXXFLAGS) -o $(OBJDIR)test.o -c test.cpp

clean:
	$(RM) -- $(test_OBJS) $(test2_OBJS) $(test3_OBJS)

distclean: clean
	$(RM) -- $(TARGETS)

install: $(TARGETS)
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)test$(EXEEXT) $(DESTDIR)$(BINDIR)/test$(EXEEXT)

uninstall:
	$(RM) -- $(DESTDIR)$(BINDIR)/test$(EXEEXT)

.PHONY: all clean distclean install uninstall
