TARGETS	= $(OBJDIR)test
OBJDIR	=
PREFIX	= /usr/local
DESTDIR	=
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

$(OBJDIR)test:
	./script.sh -P "/somewhere/else" -- "$(OBJDIR)test"

clean:
	$(RM) -- $(test_OBJS)
	./script.sh -c -P "/somewhere/else" -- "test"

distclean: clean
	$(RM) -- $(TARGETS)

install: $(TARGETS)
	./script.sh -P "$(DESTDIR)/somewhere/else/again" -i -- "$(OBJDIR)test"

uninstall:
	./script.sh -P "$(DESTDIR)/somewhere/else/again" -u -- "test"

.PHONY: all clean distclean install uninstall
