TARGETS	= $(OBJDIR)test phony
OBJDIR	=
PREFIX	= /usr/local
DESTDIR	=
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

$(OBJDIR)test:
	./script.sh -P "/somewhere/else" -- "$(OBJDIR)test"

phony:
	./script.sh -P "$(PREFIX)" -- "phony"

clean:
	$(RM) -- $(test_OBJS) $(phony_OBJS)
	./script.sh -c -P "/somewhere/else" -- "test"
	./script.sh -c -P "$(PREFIX)" -- "phony"

distclean: clean
	$(RM) -- $(TARGETS)

install: $(TARGETS)
	./script.sh -P "$(DESTDIR)/somewhere/else/again" -i -- "$(OBJDIR)test"
	./script.sh -P "$(DESTDIR)$(PREFIX)" -i -- "phony"

uninstall:
	./script.sh -P "$(DESTDIR)/somewhere/else/again" -u -- "test"
	./script.sh -P "$(DESTDIR)$(PREFIX)" -u -- "phony"

.PHONY: all clean distclean install uninstall phony
