TARGETS	= $(OBJDIR)test phony s\ p\ a\ c\ e\ s $(OBJDIR)s\ p\ a\ c\ e\ s\ 2
OBJDIR	=
PREFIX	= /usr/local
DESTDIR	=
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

$(OBJDIR)test:
	./script.sh -P "/somewhere/else" -- "$(OBJDIR)test"

$(OBJDIR)disabled: a.c b.c
	./script.sh -P "$(PREFIX)" -- "$(OBJDIR)disabled"

phony: a.c b.c
	./script.sh -P "$(PREFIX)" -O TARGET=phony -- "phony"

s\ p\ a\ c\ e\ s: $(OBJDIR)s\ p\ a\ c\ e\ s\ 2
	./s\ c\ r\ i\ p\ t.sh -P "$(PREFIX)" -- "s p a c e s"

$(OBJDIR)s\ p\ a\ c\ e\ s\ 2:
	./s\ c\ r\ i\ p\ t.sh -P "$(PREFIX)" -- "$(OBJDIR)s p a c e s 2"

clean:
	./script.sh -c -P "/somewhere/else" -- "$(OBJDIR)test"
	./script.sh -c -P "$(PREFIX)" -- "$(OBJDIR)disabled"
	./script.sh -c -P "$(PREFIX)" -O TARGET=phony -- "phony"
	./s\ c\ r\ i\ p\ t.sh -c -P "$(PREFIX)" -- "s p a c e s"
	./s\ c\ r\ i\ p\ t.sh -c -P "$(PREFIX)" -- "$(OBJDIR)s p a c e s 2"

distclean: clean
	$(RM) -- $(TARGETS)

install: all
	./script.sh -P "$(DESTDIR)/somewhere/else/again" -i -- "$(OBJDIR)test"
	./script.sh -P "$(DESTDIR)$(PREFIX)" -i -O TARGET=phony -- "phony"
	./s\ c\ r\ i\ p\ t.sh -P "$(DESTDIR)$(PREFIX)" -i -- "s p a c e s"
	./s\ c\ r\ i\ p\ t.sh -P "$(DESTDIR)$(PREFIX)" -i -- "$(OBJDIR)s p a c e s 2"

uninstall:
	./script.sh -P "$(DESTDIR)/somewhere/else/again" -u -- "test"
	./script.sh -P "$(DESTDIR)$(PREFIX)" -u -O TARGET=phony -- "phony"
	./s\ c\ r\ i\ p\ t.sh -P "$(DESTDIR)$(PREFIX)" -u -- "s p a c e s"
	./s\ c\ r\ i\ p\ t.sh -P "$(DESTDIR)$(PREFIX)" -u -- "s p a c e s 2"

.PHONY: all clean distclean install uninstall phony s\ p\ a\ c\ e\ s
